package com.example.worker_service;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.Instant;

/**
 * Job entity persisted in the worker service database.
 */
@Entity
@Table(name = "jobs")
@Data
public class Job {
    
    // Unique job identifier generated by JPA.
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    // Serialized task payload data.
    @Column(nullable = false)
    private String payload;

    // Retry tracking fields.
    private int attemptCount = 0;
    private int maxAttempts = 3;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private JobStatus status;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private Instant updatedAt;

    public enum JobStatus {
        PENDING, PROCESSING, COMPLETED, FAILED
    }

    @PrePersist
    protected void onCreate() {
        if (this.status == null) {
            this.status = JobStatus.PENDING;
        }
    }
}