package com.example.producerapi;
import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * Job entity persisted in the jobs table.
 */
@Entity
@Table(name = "jobs")
@Data
public class Job {
    
    // Unique identifier generated by JPA.
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    // Payload content for the job.
    @Column(nullable = false)
    private String payload;

    // Attempt counter and retry policy.
    private int attemptCount = 0;
    private int maxAttempts = 3;

    // Current processing state saved as a string.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private JobStatus status;

    // Audit timestamps managed by entity callbacks.
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    // Possible lifecycle states for a job.
    public enum JobStatus {
        PENDING, PROCESSING, COMPLETED, FAILED
    }

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        status = JobStatus.PENDING;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}